version: '1'
services:
  uptime-kuma:
    container_name: uptime-kuma
    hostname: uptime-kuma
    image: louislam/uptime-kuma:2.0.0-beta.0
    restart: unless-stopped
#    ports: #if you plan to have a container fully behind Traefik, you can completely comment out this section.
#      - 3000:3000
#      - 3001:3001
    networks:
        - proxynet
    volumes:
      - appdata:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro #this is not normal for containers, and is used for apps that need to read dockers config/containers. In this case, to allow UptimeKuma to see the status of containers.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`remote-status.domain.com`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=https"
      - "traefik.http.routers.uptime-kuma.tls=true"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001" #this is the port for the app, that you would ordinarily put under 'ports' above, to allow Traefik to know where to route too.
        
# Networks
networks:
  proxynet:
    name: proxynet
    
# Volumes
volumes:
  appdata:
    driver: local
