version: "3.8"
services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    ports:
      - "1.2.3.4:9001:9001" # First IP binding
      - "5.6.7.8:9001:9001" # Second IP binding
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
