version: '3'
services:
  poste-io:
    container_name: poste-io
    hostname: mail.domain.com
    image: analogic/poste.io:2.4.10
    environment:
      - TZ=Americas/New_York
      - HTTP_PORT=8080
      - HTTPS_PORT=4433
      - HTTPS=OFF
    restart: unless-stopped
    ports:
      #these is specified here instead of Traefik, as the passthrough doesnt appear to work correctly, nor showing source IP addresses.
      # SMTP
      - 25:25/tcp 
      # IMAPS
      - "1.2.3.4:993:993"
      - "5.6.7.8:993:993"
      # SMTPS
      - "1.2.3.4:587:587"
      - "5.6.7.8:587:587"
    volumes:
      - appdata:/data
      - /etc/localtime:/etc/localtime:ro
      - /data/certs/poste_certs/domain.com/privatekey.pem:/data/ssl/server.key:ro
      - /data/certs/poste_certs/private/letsencrypt.pem:/data/ssl/ca.crt:ro
      - /data/certs/poste_certs/domain.com/certificate.pem:/data/ssl/server.crt:ro
    networks:
      - proxynet
    labels:
      - "traefik.enable=true"
      # GUI/HTTPS
      - "traefik.http.routers.poste-io.rule=Host(`mail.domain.com`) || Host(`autodiscover.domain.com`) || Host(`autoconfig.domain.com`) || Host(`email.domain.com`) || Host(`imap.domain.com`) || Host(`pop3.domain.com`) || Host(`smtp.domain.com`)"
      - "traefik.http.routers.poste-io.entrypoints=https"
      - "traefik.http.routers.poste-io.tls=true"
      - "traefik.http.services.poste-io.loadbalancer.server.port=8080"
      - "traefik.http.services.poste-io.loadbalancer.passHostHeader=true"

# Networks
networks:
  proxynet:
    name: proxynet
    external: true
    
# Volumes
volumes:
  appdata:
    driver: local
